// Generated by CoffeeScript 1.6.3
(function() {
  window.corduroy = (function() {
    var corduroy;
    corduroy = function() {};
    corduroy.matches = (function() {
      return document.body.matches || document.body.webkitMatchesSelector || document.body.mozMatchesSelector || document.body.msMatchesSelector;
    })();
    corduroy.on = function(node, type, fn) {
      node.addEventListener(type, fn, false);
      return node;
    };
    corduroy.off = function(node, type, fn) {
      node.removeEventListener(type, fn, false);
      return node;
    };
    corduroy.trigger = function(node, type, data) {
      var e;
      if (data == null) {
        data = {};
      }
      e = document.createEvent('HTMLEvents');
      e.initEvent(type, true, true);
      e.eventName = type;
      e.target = node;
      e.data = data;
      node.dispatchEvent(e);
      return node;
    };
    corduroy.tapon = function(node, fn) {
      node.addEventListener('click', corduroy.prevented, false);
      if (typeof Hammer === "function") {
        Hammer(node, {
          stop_browser_behavior: false
        }).on('tap doubletap', fn);
      }
      return node;
    };
    corduroy.tapoff = function(node, fn) {
      node.removeEventListener('click', corduroy.prevented, false);
      if (typeof Hammer === "function") {
        Hammer(node).off('tap doubletap', fn);
      }
      return node;
    };
    corduroy.prevented = function(e) {
      return e.preventDefault();
    };
    corduroy.parentSelector = function(element, selector) {
      while (element) {
        if (corduroy.matches.bind(element)(selector)) {
          return element;
        } else {
          element = element.parentNode;
        }
      }
      return false;
    };
    corduroy.remove = function(node) {
      return node.parentNode.removeChild(node);
    };
    if (!window.$) {
      window.$ = corduroy;
    }
    return corduroy;
  })();

}).call(this);
